### ISSUE TITLE
API de nome "vulnerável" ainda

### ISSUE THREAD

**Issue by Doges** [Kiny-Kiny/Kiny-Painel#11]
Tenta me dar uma chamada no Discord (Doges#5183) qualquer coisa ou na dm de algum lugar pra tentar te ajudar a arrumar, pode ser twitter ou qualquer coisa que o pessoal ainda pode abusar dessa api infelizmente, só não falo o método aqui pra não ficar público, abraços.

**Comment by Kiny-Kiny** [comment]
Ok ok, vou chamar vc lá:D
