### ISSUE TITLE
Está online?

### ISSUE THREAD

**Issue by Alternativo23** [Kiny-Kiny/Kiny-Painel#13]

**Comment by Kiny-Kiny** [comment]
Pq vc fez uma issue? Man, tá ON tudo, exceto a consulta de número, nome de mãe e CPF, ele agr só puxa pelo nome.

**Comment by CrowleyFergus** [comment]
_O_i, lindo. Solteiro?_

**Comment by erik2039** [comment]
Ouxi Du nada aparece isso no meu e-mail

Em qui, 13 de mai de 2021 13:41, CrowleyFergus ***@***.***>
escreveu:

**Comment by CrowleyFergus** [comment]
Ksksksksk kiny me respondeu🤏😎

Em qui, 13 de mai de 2021 13:54, erik2039 ***@***.***>
escreveu:

**Comment by erik2039** [comment]
Eu falo com ele no zap

Em qui, 13 de mai de 2021 13:57, CrowleyFergus ***@***.***>
escreveu:
