### ISSUE TITLE
API "numero"

### ISSUE THREAD

**Issue by sacodeba** [Kiny-Kiny/Kiny-Painel#14]
Olá estou com dúvidas se a api de numero irá voltar?
E também a questão se está api irá ser pública se nos poderemos utilizar
Esta api? Mais uma questão q está me entrigando é sobre a api de nome é
Email obrigado pela atenção kiny    :)

**Comment by Kiny-Kiny** [comment]
Bem, a quando a API se número retornar, ela irá ser totalmente criptografada para impedir q terceiros usem a API em serviços pagos.
