### ISSUE TITLE
Creditos

### ISSUE THREAD

**Issue by p0isonBR** [Kiny-Kiny/Kiny-Painel#4]
Minhas ferramentas sao open-source, porem como toda ferramenta open-source, a unica coisa que pedimos sao creditos, voce usa pelo que vi, 4 ou 5 tools minhas. Se quiser ser um desenvolvedor um dia, comece corretamente. Boa sorte com o painel.

**Comment by Kiny-Kiny** [comment]
Entendo, mas as únicas ferramentas que eu usei que são "suas", foram a de CPF e de CC Checker, o resto já estava em desenvolvimento ou já estava no script.

**Comment by p0isonBR** [comment]
Tudo bem cara, boa sorte.

**Comment by Kiny-Kiny** [comment]
Obg :)
